
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dotnetcoreapp
  name: dotnetcoreapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: dotnetcoreapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dotnetcoreapp
    spec:
      containers:
      - image: docker.io/bbachin1/dotnetcoreapp
        name: dotnetcoreapp
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 8080 
status: {}