apiVersion: v1
kind: Pod
metadata:
  name: dotnetcoreapp
spec:
  containers:
    - image: docker.io/bbachin1/dotnetcoreapp
      name: dotnetcoreapp
      imagePullPolicy: Always
      resources: {}
      ports:
        - containerPort: 8080